env: "local"

http_server:
  address: "localhost:8081"
  timeout: 5s
  idle_timeout: 60s

jwt:
  secret_key: "aboba"
  access_token_ttl: 30m
  refresh_token_ttl: 48h

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "12345"
  dbname: "coursedb"


elasticsearch:
  hosts:
    - "http://localhost:9200"
  index: "courses"
  password: "12345"

minio:
  endpoint: "localhost:9000"
  access_key: "ROOTNAME"
  secret_key: "CHANGEME123"
  use_ssl: false
  buckets:
    course_logos:
      name: "course-logos"
      presign_ttl: 15m